### Sobre a Biblioteca

Numpy é uma biblioteca de álgebra linear para Python.

É o bloco de construção de **todas** as outras bibliotecas de análise de dados.

É extremamente rápida, uma vez que seus principais métodos foram compilados em C.

### Arrays Numpy

Numpy arrays serão nossa principal ferramenta ao longo do curso.

Numpy arrays essencialmente vêm de duas formas: **vetores e matrizes**.

Vetores são estritamente arrays de 1-d. Matrizes são 2-d (porém, você pode notar que uma matriz pode ter apenas 1 linha ou coluna).

### Primeiros Passos

In [2]:
import numpy as np

In [4]:
minha_lista = [1, 2, 3]

In [5]:
minha_lista

[1, 2, 3]

In [9]:
# converter para numpy array vetor 1-d
np.array(minha_lista)

array([1, 2, 3])

In [10]:
matriz = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
# converter para numpy array matriz 2-d
np.array(matriz)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Métodos

In [15]:
# shift + tab no jupyter com cursos em um método para chamar o 'man'

np.arange(0, 10) # cria um array no range definido (0 até 10 - 1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(0, 10, 2) # terceiro parâmetro é o step

array([0, 2, 4, 6, 8])

In [19]:
np.zeros(3) # cria matriz de zeros com x elementos

array([0., 0., 0.])

In [20]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
np.ones((3, 3)) # cria matriz de uns com x elementos

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [24]:
np.eye(4) # cria matriz identidade no grau x

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [28]:
np.linspace(0, 10, 2) # retorna numeros igualmente espacados no intervalo especificado

array([ 0., 10.])

In [27]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [31]:
np.random.rand(5) # cria x numeros aleatorios de 0 a 1 em uma distribuicao uniforme

array([0.41555188, 0.42870554, 0.28693683, 0.97600443, 0.61108106])

In [32]:
np.random.rand(5) * 100

array([89.93696894,  9.39454053, 80.71532099,  6.64940388, 77.13598487])

In [34]:
np.random.rand(5, 4) # matriz 5x4

array([[0.13915309, 0.52191312, 0.41099565, 0.73738725],
       [0.51142799, 0.51297039, 0.62239366, 0.43283994],
       [0.33414353, 0.59146324, 0.52697292, 0.28489906],
       [0.79834628, 0.36348434, 0.16357075, 0.58942691],
       [0.99580674, 0.58457364, 0.30554489, 0.12863036]])

In [35]:
np.random.randn(4) # mesma coisa só que com distribuicao normal, media 0 desvio padrao 1

array([ 0.61665669, -1.97607913, -1.30163087, -0.07768396])

In [37]:
np.random.randint(0, 100, 10) # 10 numeros entre 0 e 100, inteiros

array([71, 25, 13, 11, 69, 18, 14, 43, 43, 69])

In [38]:
arr = np.random.rand(25)

In [39]:
arr

array([0.54862065, 0.31383324, 0.5382735 , 0.68604735, 0.33648355,
       0.99938541, 0.7178071 , 0.84496288, 0.37181259, 0.15768183,
       0.18278095, 0.68277572, 0.73794178, 0.71186199, 0.61465199,
       0.78625156, 0.51203626, 0.50592382, 0.2343573 , 0.61484905,
       0.13961486, 0.91223915, 0.5794369 , 0.58114533, 0.51575662])

In [42]:
arr.reshape((5, 5)) # transforma de vetor para matriz

array([[0.54862065, 0.31383324, 0.5382735 , 0.68604735, 0.33648355],
       [0.99938541, 0.7178071 , 0.84496288, 0.37181259, 0.15768183],
       [0.18278095, 0.68277572, 0.73794178, 0.71186199, 0.61465199],
       [0.78625156, 0.51203626, 0.50592382, 0.2343573 , 0.61484905],
       [0.13961486, 0.91223915, 0.5794369 , 0.58114533, 0.51575662]])

In [43]:
arr.shape

(25,)

In [45]:
arr.reshape((5, 5)).shape

(5, 5)

In [47]:
arr.max() # retorna maior valor

0.9993854087006793

In [48]:
arr.min() # retorna menor valor

0.13961485728270984

In [49]:
arr.argmax() # retorna indice do maior valor

5

In [50]:
arr.argmin() # retorna indice do menor valor

20

### Indexação e Fatiamento

In [4]:
arr = np.arange(0, 30, 3)

In [5]:
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [6]:
# acesso via indice
arr[3]

9

In [7]:
arr[2:5] # acessar indice 2 até 5 - 1

array([ 6,  9, 12])

In [8]:
arr[:5] # acessar todos  até 5 - 1

array([ 0,  3,  6,  9, 12])

In [9]:
arr[2:] # acessar todos a partir do indice 2

array([ 6,  9, 12, 15, 18, 21, 24, 27])

In [10]:
arr[2:] = 100

In [12]:
arr

array([  0,   3, 100, 100, 100, 100, 100, 100, 100, 100])

In [14]:
arr[2:] = arr[2:] + 1

In [15]:
arr

array([  0,   3, 101, 101, 101, 101, 101, 101, 101, 101])

In [39]:
arr = np.arange(50)

In [17]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [40]:
arr = arr.reshape((5, 10))

In [19]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [20]:
arr.shape

(5, 10)

In [22]:
#arr[linha][coluna]
arr[:3][:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [23]:
arr2 = arr[:3]

In [24]:
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [25]:
arr2[:] = 100

In [28]:
arr2

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100]])

In [29]:
arr

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49]])

(arr2 é referência do arr, e não uma cópia)

In [31]:
arr2 = arr[:3].copy()

In [32]:
arr2

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100]])

In [36]:
arr2[:] = 200

In [37]:
arr2

array([[200, 200, 200, 200, 200, 200, 200, 200, 200, 200],
       [200, 200, 200, 200, 200, 200, 200, 200, 200, 200],
       [200, 200, 200, 200, 200, 200, 200, 200, 200, 200]])

In [38]:
arr

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49]])

In [41]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [43]:
#arr[linha,coluna]
arr[1:4,5:]

array([[15, 16, 17, 18, 19],
       [25, 26, 27, 28, 29],
       [35, 36, 37, 38, 39]])

In [46]:
arr[0,:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
arr[:,0]

array([ 0, 10, 20, 30, 40])

In [49]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [57]:
# quais numeros maiores que 50
arr > 25

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [55]:
bol = arr > 25

In [56]:
arr[bol]

array([26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42,
       43, 44, 45, 46, 47, 48, 49])

In [66]:
bol = (arr % 2 == 0)

In [69]:
arr[bol]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [58]:
array = np.linspace(0, 100, 30)
array

array([  0.        ,   3.44827586,   6.89655172,  10.34482759,
        13.79310345,  17.24137931,  20.68965517,  24.13793103,
        27.5862069 ,  31.03448276,  34.48275862,  37.93103448,
        41.37931034,  44.82758621,  48.27586207,  51.72413793,
        55.17241379,  58.62068966,  62.06896552,  65.51724138,
        68.96551724,  72.4137931 ,  75.86206897,  79.31034483,
        82.75862069,  86.20689655,  89.65517241,  93.10344828,
        96.55172414, 100.        ])

In [59]:
array.shape

(30,)

In [60]:
array = array.reshape(3, 10)

In [61]:
array

array([[  0.        ,   3.44827586,   6.89655172,  10.34482759,
         13.79310345,  17.24137931,  20.68965517,  24.13793103,
         27.5862069 ,  31.03448276],
       [ 34.48275862,  37.93103448,  41.37931034,  44.82758621,
         48.27586207,  51.72413793,  55.17241379,  58.62068966,
         62.06896552,  65.51724138],
       [ 68.96551724,  72.4137931 ,  75.86206897,  79.31034483,
         82.75862069,  86.20689655,  89.65517241,  93.10344828,
         96.55172414, 100.        ]])

In [62]:
array.shape

(3, 10)

In [63]:
array[0:2, 2]

array([ 6.89655172, 41.37931034])

In [70]:
arr = np.arange(0, 16)

In [71]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

### Operações com Arrays

In [90]:
# operacoes indice a indice
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [74]:
 arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [75]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225])

In [86]:
arr ** 3

array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000,
       1331, 1728, 2197, 2744, 3375], dtype=int32)

In [79]:
# numpy trata divisão impossível e coloca NaN
arr / arr

C:\Users\Lucas\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.])

In [84]:
# numpy trata divisão por zero e coloca infinito
1 / arr

C:\Users\Lucas\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       , 0.09090909, 0.08333333, 0.07692308, 0.07142857,
       0.06666667])

In [91]:
# superescalares
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115])

In [92]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90,
        -89,  -88,  -87,  -86,  -85])

In [94]:
# raiz quadrada de cada elemento
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335])

In [95]:
# exponenciacao
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06])

In [97]:
# media total
np.mean(arr)

7.5

In [98]:
# desvio padrao
np.std(arr)

4.6097722286464435

In [100]:
# seno
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
        0.65028784])

In [101]:
np.max(arr)

15

In [102]:
np.min(arr)

0

In [104]:
arr.max()

15

In [105]:
arr.min()

0